INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','a_0','Activity unit',46134,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','a_0','Rolling mean employees',0,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','a_0','Salaries and wages paid',279,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','a_0','Sales, government funding, grants and subsidies',8187,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','a_0','Total income',8866,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','a_0','Total expenditure',7618,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','a_0','Operating profit before tax',770,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','a_0','Total assets',55700,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','a_0','Fixed tangible assets',32155,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','b_1-5','Activity unit',21777,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','b_1-5','Rolling mean employees',38136,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','b_1-5','Salaries and wages paid',1435,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','b_1-5','Sales, government funding, grants and subsidies',13359,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','b_1-5','Total income',13771,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','b_1-5','Total expenditure',12316,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','b_1-5','Operating profit before tax',1247,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','b_1-5','Total assets',52666,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','b_1-5','Fixed tangible assets',31235,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','c_6-9','Activity unit',1965,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','c_6-9','Rolling mean employees',13848,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','c_6-9','Salaries and wages paid',467,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','c_6-9','Sales, government funding, grants and subsidies',3060,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','c_6-9','Total income',3114,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','c_6-9','Total expenditure',2895,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','c_6-9','Operating profit before tax',223,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','c_6-9','Total assets',9323,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','c_6-9','Fixed tangible assets',5482,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','d_10-19','Activity unit',1140,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','d_10-19','Rolling mean employees',14850,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','d_10-19','Salaries and wages paid',477,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','d_10-19','Sales, government funding, grants and subsidies',2396,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','d_10-19','Total income',2438,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','d_10-19','Total expenditure',2344,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','d_10-19','Operating profit before tax',126,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','d_10-19','Total assets',6524,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','d_10-19','Fixed tangible assets',3649,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','e_20-49','Activity unit',480,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','e_20-49','Rolling mean employees',13983,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','e_20-49','Salaries and wages paid',410,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','e_20-49','Sales, government funding, grants and subsidies',1806,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','e_20-49','Total income',1885,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','e_20-49','Total expenditure',1773,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','e_20-49','Operating profit before tax',80,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','e_20-49','Total assets',3984,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','e_20-49','Fixed tangible assets',1676,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','f_50-99','Activity unit',111,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','f_50-99','Rolling mean employees',7419,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','f_50-99','Salaries and wages paid',200,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','f_50-99','Sales, government funding, grants and subsidies',1075,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','f_50-99','Total income',1170,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','f_50-99','Total expenditure',1056,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','f_50-99','Operating profit before tax',39,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','f_50-99','Total assets',2067,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','f_50-99','Fixed tangible assets',930,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','g_100-199','Activity unit',27,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','g_100-199','Rolling mean employees',3522,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','g_100-199','Salaries and wages paid',86,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','g_100-199','Sales, government funding, grants and subsidies',341,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','g_100-199','Total income',364,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','g_100-199','Total expenditure',333,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','g_100-199','Operating profit before tax',37,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','g_100-199','Total assets',807,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','g_100-199','Fixed tangible assets',C,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','h_200+','Activity unit',15,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','h_200+','Rolling mean employees',6120,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','h_200+','Salaries and wages paid',173,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','h_200+','Sales, government funding, grants and subsidies',920,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','h_200+','Total income',1034,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','h_200+','Total expenditure',850,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','h_200+','Operating profit before tax',93,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','h_200+','Total assets',2555,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','h_200+','Fixed tangible assets',C,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','i_Industry_Total','Activity unit',71652,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','i_Industry_Total','Rolling mean employees',97878,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','i_Industry_Total','Salaries and wages paid',3527,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','i_Industry_Total','Sales, government funding, grants and subsidies',31145,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','i_Industry_Total','Total income',32642,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','i_Industry_Total','Total expenditure',29185,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','i_Industry_Total','Operating profit before tax',2616,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','i_Industry_Total','Total assets',133625,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'A','Agriculture, Forestry and Fishing','i_Industry_Total','Fixed tangible assets',76626,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','a_0','Activity unit',333,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','a_0','Rolling mean employees',0,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','a_0','Salaries and wages paid',98,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','a_0','Sales, government funding, grants and subsidies',2111,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','a_0','Total income',2271,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','a_0','Total expenditure',1673,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','a_0','Operating profit before tax',636,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','a_0','Total assets',11988,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','a_0','Fixed tangible assets',3579,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','b_1-5','Activity unit',168,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','b_1-5','Rolling mean employees',360,'COUNT')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','b_1-5','Salaries and wages paid',50,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','b_1-5','Sales, government funding, grants and subsidies',443,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','b_1-5','Total income',462,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','b_1-5','Total expenditure',411,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','b_1-5','Operating profit before tax',89,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','b_1-5','Total assets',1213,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','b_1-5','Fixed tangible assets',771,'DOLLARS(millions)')
INSERT INTO ETL_CHALLENGE_1.DATA_EXAMPLE VALUES(2011,'B','Mining','c_6-9','Activity unit',21,'COUNT')